export const COLORS = [
    { nombre: "Rojo", valor: "red", hex: "#e5484d" },
    { nombre: "Tomate", valor: "tomato", hex: "#e54d2e" },
    { nombre: "Naranja", valor: "orange", hex: "#f76b15" },
    { nombre: "Marrón", valor: "brown", hex: "#ad7f58" },
    { nombre: "Rosa", valor: "pink", hex: "#d6409f" },
    { nombre: "Plum", valor: "plum", hex: "#ab4aba" },
    { nombre: "Iris", valor: "iris", hex: "#5b5bd6" },
    { nombre: "Índigo", valor: "indigo", hex: "#3e63dd" },
    { nombre: "Azul", valor: "blue", hex: "#0090ff" },
    { nombre: "Cian", valor: "cyan", hex: "#00a2c7" },
    { nombre: "Jade", valor: "jade", hex: "#29a383" },
    { nombre: "Verde", valor: "green", hex: "#30a46c" },
    { nombre: "Hierba", valor: "grass", hex: "#46a758" },
]